### ISSUE TITLE
startup warning : _extract_number_re.split

### ISSUE THREAD

**Issue by aureooms** [hut/ranger#386] opened 2015-10-03 11:44 UTC
Starting ranger now shows the following warning message
![2015-10-03-133334_1251x41](https://cloud.githubusercontent.com/assets/5165674/10262702/8fc12f2e-69d3-11e5-843b-6408b73241c4.png)

Seems related to http://stackoverflow.com/questions/29988595/python-regex-splitting-on-pattern-match-that-is-an-empty-string.

**Comment by shaggytwodope** [comment] 2015-10-03 11:54
duplicate of #381

**Comment by hut** [comment] 2015-10-03 18:18
Fixed in #385

**Closed** 2015-10-03 18:18 UTC
